<style>
    a:link,
    a:visited
    {
        color: #666666;
    }

    span#zf-name
    {
        color: #BBBBBB;
    }

    div#welcome
    {
        color: #AAAAAA;
        /*background-color: #EEE;*/
        width:  400px;
        height: 200px;
        /*border: 2px solid #CCCCCC;*/
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        /*background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);*/
        height: 100%;
    }
</style>
<div id="welcome" align="center">
    <h1>Welcome to the <span id="zf-name">Linmukong Space!</span></h1>

    <h3>This is my project's main page</h3>

    <div id="more-information">
        <!--<p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>-->
<!--        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>-->
    </div>
</div>